/* Name: Hao Nguyen
 * Class: CSC 4380
 * Title: Assignment 3 - Caesar's Cipher
 * Date: September 16, 2018
 * Campus ID: hnguyen154
 */

import java.awt.*;
import java.util.*;
import javax.swing.*;
    
public class Csc4380Hnguyen154Assignment3 extends javax.swing.JFrame {

    
    public Csc4380Hnguyen154Assignment3() {
        initComponents();
        centerWindow(this); //<-- Set to the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        encryptButton = new javax.swing.JButton();
        decryptButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        keyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputField = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        keyField = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        messageLabel = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Clear = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Close = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputLabel.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        outputLabel.setText("OUTPUT:");

        inputLabel.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        inputLabel.setText("INPUT:");

        encryptButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        encryptButton.setText("ENCRYPT");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });

        decryptButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        decryptButton.setText("DECRYPT");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        titleLabel.setText("CASAER'S CIPHER");

        keyLabel.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        keyLabel.setText("ENTER A KEY: ");

        inputField.setColumns(20);
        inputField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inputField.setLineWrap(true);
        inputField.setRows(5);
        jScrollPane1.setViewportView(inputField);

        outputField.setEditable(false);
        outputField.setColumns(20);
        outputField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        outputField.setRows(5);
        jScrollPane3.setViewportView(outputField);

        keyField.setColumns(4);
        keyField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        keyField.setRows(1);
        keyField.setTabSize(1);
        keyField.setToolTipText("Please enter an integer value.");
        jScrollPane2.setViewportView(keyField);

        messageLabel.setEditable(false);
        messageLabel.setColumns(5);
        messageLabel.setRows(1);
        messageLabel.setTabSize(1);
        messageLabel.setSelectedTextColor(new java.awt.Color(255, 51, 51));
        jScrollPane4.setViewportView(messageLabel);

        File.setText("File");

        Clear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        File.add(Clear);
        File.add(jSeparator1);

        Close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        File.add(Close);

        MenuBar.add(File);

        Help.setText("Help");
        MenuBar.add(Help);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(decryptButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(encryptButton)))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(0, 0, 0)
                .addComponent(keyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encryptButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decryptButton)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        // TODO add your handling code here:
        try{
            
            //clear out existence output
            outputField.setText("");
            
            //Get Message from user
            String inputText = inputField.getText();
            //Get the key
            int key = Integer.parseInt(keyField.getText());
            
            //check for special character
            specialChar(inputText);
            
            //Produce encrypted string
            String outputText = encrypt(inputText, key);
            outputField.setText(outputText);
            
        }
        catch (NumberFormatException e){
            //Not an integer
            messageLabel.setText("Please enter an integer value.");
            
        }
        catch (Exception exception){
            messageLabel.setText("Please enter a message without special characters.");
        }
    }//GEN-LAST:event_encryptButtonActionPerformed
    /**
     * 
     * @param inputText
     * @throws Exception 
     */
    //check for special character
    private void specialChar(String inputText) throws Exception {
        for (int i = 0; i < inputText.length(); i++){
            if(inputText.charAt(i) < 32 || inputText.charAt(i) > 126){ 
                throw new Exception();
            }
        }
    }
    /**
     * 
     * @param inputText
     * @param key
     * @return 
     */
    private String encrypt(String inputText, int key){       
        String output = "";
        //shift the array
        for (int i=0; i<inputText.length(); i++){
            output = output + (char)((int)inputText.charAt(i)+key%256);
        }
       
        return output;
    }
    
    
    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        //clear output field
        outputField.setText("");
           
        //Get the output value 
        String inputText = inputField.getText();
        int key = Integer.parseInt(keyField.getText());
        String output = encrypt(inputText, key);
        
        //do the decryption
        String newOutput = "";
        for (int i=0; i<output.length(); i++){
            newOutput = newOutput + (char)((int)output.charAt(i)-key + 256 %256);
        }        
        outputField.setText(newOutput);
    }//GEN-LAST:event_decryptButtonActionPerformed
   
        
    
    
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        outputField.setText("");
        inputField.setText("");
        keyField.setText("");
        messageLabel.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed
    
    //Set the window to the center of the screen (Credit: https://grid.cs.gsu.edu/~cfrederick/csc4380/?page=mat)
    public static void centerWindow(JFrame frame) {
    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
    int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
    frame.setLocation(x, y);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */   
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Csc4380Hnguyen154Assignment3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Csc4380Hnguyen154Assignment3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Csc4380Hnguyen154Assignment3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Csc4380Hnguyen154Assignment3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Csc4380Hnguyen154Assignment3().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Clear;
    private javax.swing.JMenuItem Close;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton decryptButton;
    private javax.swing.JButton encryptButton;
    private javax.swing.JTextArea inputField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea keyField;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JTextArea messageLabel;
    private javax.swing.JTextArea outputField;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
